### ISSUE TITLE
Changing template

### ISSUE THREAD

**Issue by MacRolt** [ruddj/SportsAdmin#3]
Hi.
I love this carnival database - thank you.  I had set up my own, but yours is awesome, very user friendly, thank you.

When I generate the templates, I change them to portrait as that suits my school better.  Is there a way to alter the template slightly?  By changing to portrait view I get a second page for everything that I don't really need, and rather than wasting paper, I'd like to remove a section so it doesn't print.

Also, it would be great if for field events I could add more columns for 1st attempt, 2nd attempt, third attempt, rather than just best.  We tend to let them have a go, measure and record - especially for long jump and high jump.

**Comment by ruddj** [comment]
Hi Mac, 
I'm glad to hear you are finding it useful.

Do you mean the Web templates or the output from reports? Both of these should already be in Portrait view.
Here is an example of our recent Athletics Carnival that I generated using the web sites export. We print this in Portrait mode.
http://www.sydneyboyshigh.com/documents/carnivals/2017/ath/etoa.htm

For the field events we have the marshals use a paper form that has the multiple attempts recorded on it and we just enter the best result for scoring and record keeping.
[AA Field Event Recording sheets.pdf](https://github.com/ruddj/SportsAdmin/files/1050777/AA.Field.Event.Recording.sheets.pdf)

**Comment by MacRolt** [comment]
I'll send you a copy tomorrow. I'm having trouble generating it tonight (might be user error tonight, I'm exhausted!) 

Is there a way to print the final results in place order? I found how to print the results but they come in alphabetical order. 

Thanks 

Jae Rolt, JP
Teacher Librarian
Cessnock West PS
MANTLE Committee Member

**Comment by ruddj** [comment]
Hi Jae,
 The two main reports you want are **Competitor Places** and **Competitor Results**. 
Only confusing thing is with **Competitor Results** print version it is the best results, including the heats, so if someone ran faster in a heat than the final it would include them. This is changed in the web version to be based more on place.

**Comment by MacRolt** [comment]
Hi James.

I used your sports Admin program last year for our carnival and it was
BRILLIANT.

Just wondering if it can be run on a Mac?

**Comment by ruddj** [comment]
Hi Jae,
 I am glad to hear it worked well. We just had our Swimming Carnival today and it worked with no problems, although I discovered I had introduced a minor annoying bug that pops up occasionally, which I will fix in next few days.

Regarding running on Mac, unfortunately Microsoft only release MS Access for Windows OS. So your only option is to run Parallels or Boot Camp on the Mac to have a virtual Windows operating system with Office installed.
Sorry, but out of my hands.

**Comment by MacRolt** [comment]
Thanks James. Insert forehead slap! Obviously start of year tired and didn’t even think about the fact it is run through access !!! 

Thanks for the quick reply. 

Enjoy your day 😁

Jae Rolt, JP
Teacher Librarian
Cessnock West PS
MANTLE Committee Member
